version: '3.8'

services:
  # front:
  #   build: ./front
  #   ports:
  #     - "8080:3000"
  #     - "24678:24678"
  #   volumes:cd ../
  #     - ./front:/app
  #     - /app/node_modules
  #   depends_on:
  #     - api
  
  api:
    build: 
      context: './api'
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./api:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    ports:
      - "8090:80"
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file:
      .env
    depends_on:
      - mysql

volumes:
  db_data:
    driver: local